### ISSUE TITLE
does express-mailer support express4?

### ISSUE THREAD

**Issue by xuchangeu** [RGBboy/express-mailer#31]
Does express-mailer support express4?
while I config the code lie instruction:

`mailer.extend(app,_config.mailConfig.from);`

the _config.mailConfig.from is like

`{
    from: 'no-reply@ucloud.cn',
    template: '<h1>testcontent</h1>',
    host: 'smtp.qiye.163.com',
    secureConnection: true,
    port: 993,
    transportMethod: 'SMTP',
    auth: {
        name: 'foo@test.com',
        pass: 'abcd1234'
    }
}`

and now i got an error

`/Users/renjie.huang/projects/uweb/console-admin/node_modules/express-mailer/lib/express-mailer.js:112
   mailer.render = createRender(app.render.bind(app));
                                          ^

TypeError: Cannot read property 'bind' of undefined
    at Object.exports.extend (/Users/renjie.huang/projects/uweb/console-admin/node_modules/express-mailer/lib/express-mailer.js:112:43)
    at Object.<anonymous> (/Users/renjie.huang/projects/uweb/console-admin/src/controller/c_mail.js:14:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/renjie.huang/projects/uweb/console-admin/src/app.js:8:14)`

anyone know about this?

**Comment by RGBboy** [comment]
Nope, I would recommend just using node-mailer directly instead.
